### ISSUE TITLE
str_starts_with only available in PHP8

### ISSUE THREAD

**Issue by fmdelvalle** [phabelio/phabel#1]
This library uses str_starts_with in four places, but it is only available on PHP 8, which I think defeats the purpose of this transpiler. Source: https://www.php.net/manual/en/function.str-starts-with.php. Composer/Transformer.php breaks my composer update on PHP 7.4.

**Comment by fmdelvalle** [comment]
I guess this package is for doing the opposite (transpiling from 7 to 8), so I close this issue

**Comment by danog** [comment]
No, you're right, this library is for transpiling PHP 8 to PHP 5.6.
The final version of the library will automatically install all required polyfills automatically, I'm thinking of finalizing the latest details sometime this week (I tagged a few releases mainly to test requiring from packagist).

**Comment by danog** [comment]
All fixed, phabel is now ready!
