### ISSUE TITLE
Shouldn't prefix transpiled libraries?

### ISSUE THREAD

**Issue by leoloso** [phabelio/phabel#15]
This is a theoretical question, I haven't checked if an issue actually happens or not.

I can see that transpiled libraries under `vendor/phabel/transpiler71` still retain the same namespace: `Nette\Utils\Strings` is transpiled under `Nette\Utils\Strings`, not under `PhabelVendor/Nette\Utils\Strings`. Isn't that a problem?

For instance, if two libraries use `Nette\Utils\Strings`, and of them is using Phabel and the other not, couldn't that create conflicts?

**Comment by danog** [comment]
Phabel's composer plugin sets transpiled packages to `provide` the original package, as well, so this is not an issue.
Composer will resolve all conflicts, and replace the original version of the package with the transpiled one, if present.

**Comment by leoloso** [comment]
I have the impression you can still run into trouble. Say that you have interface `Cadorno`, which is in a package that is depended-upon a Phabelized library, and a non-Phabelized one, and it has this method:

```php
interface Cadorno
{
  function get(): mixed;
}
```

Then:

- The transpiled version to PHP 7.4 will change the signature to `function get();`, dropping the return type `mixed`
- `Cadorno` will be transpiled, and the transpiled version will also provide the standard version
- Somewhere in the non-transpiled code (maybe in the non-Phabelized library, or in the source project, which I guess is not transpiled) someone will implement `function get(): mixed`, not `function get()`:

```php
class SomeCadorno implements Cadorno
{
  function get(): mixed
  {
    return "Boom! 💥"
  }
}
```

Wouldn't this fail?

**Comment by danog** [comment]
If SomeCadorno is defined in the root composer project A (the one that requires somevendor/cadorno), the developer of A will already use PHP 8 locally for development, so transpilation will not be triggered.

If some other project is in turn requiring A, phabel will transpile A, even if A does not explicitly require phabel, exactly to solve covariance issues like these.
The behavior in #9 is a bug, in reality, all covariance issues inside the vendor folder should be resolved automatically.

**Comment by danog** [comment]
Now transpiled packages actively `conflict` with all versions (`*`) of the original package, forcing composer to install only the transpiled version.
