### ISSUE TITLE
[ErrorException]   Constant PHABEL_INCLUDED already defined

### ISSUE THREAD

**Issue by HosseinKeramati** [phabelio/phabel#2]
I have PHP@7.4 installed.

after running `composer require --dev phabel/phabel`
I got this error:

[ErrorException]
  Constant PHABEL_INCLUDED already defined

**Comment by danog** [comment]
That's weird, are you running the command inside the phabel repo?
You should run it inside your own repo.
Anyway already pushed a fix.
