### ISSUE TITLE
Typed properties not removed

### ISSUE THREAD

**Issue by ondrejmirtes** [phabelio/phabel#3]
Hello,
I'm trying this project on PHPStan's source code. When running this command, I'd expect the sources in `dist` directory to not contain typed properties. Or is there any additional configuration to do if I'd like to support PHP 7.1? Thanks!

```
vendor/bin/phabel run src/ dist

＊＊＊＊＊＊＊＊＊
＊ Ｐｈａｂｅｌ ＊
＊＊＊＊＊＊＊＊＊

PHP transpiler - Write and deploy modern PHP 8 code, today: https://phabel.io

Transpilation in progress...  77% (709/914)
Syntax error, unexpected ',' on line 390 while parsing /Users/ondrej/Development/phpstan/src/Command/FixerApplication.php!
Transpilation in progress... 100% (914/914)
Done!
```

**Comment by danog** [comment]
You should provide a `--target=7.1` flag to the run command: it was previously mandatory, maybe I should make it mandatory again :)

**Comment by danog** [comment]
Now the default target of the `run` command is the lowest PHP version supported by phabel, not the current version.
