### ISSUE TITLE
Docs - Clarify what publish does

### ISSUE THREAD

**Issue by ondrejmirtes** [phabelio/phabel#4]
Hi, I don't understand the magic behind the `publish` command. The README says:

> You can publish this code as a Composer package and have it automatically transpile on installation

How is this achieved?

**Comment by danog** [comment]
I'm whipping up some more detailed docs right now, in a nutshell, it takes the latest tag, and creates two subtags (`tag.9999`, `tag.9998`), one with no changes, and the other with phabel added as a main dependency, and all dependencies moved to a separate composer section to allow transpilation upon installation using the Composer plugin.

**Comment by danog** [comment]
Updated the docs, documenting all CLI API commands!
https://github.com/phabelio/phabel
