### ISSUE TITLE
The package is not transpiled when not having "type: library" or not placed under vendor/

### ISSUE THREAD

**Issue by leoloso** [phabelio/phabel#8]
I have a package with type `wordpress-plugin`, and then I configure it in `composer.json` to be installed not under `vendor/`, but under `wordpress/wp-content/plugins/`:

```json
{
  "extra": {
    "installer-paths": {
      "wordpress/wp-content/plugins/{$name}/": [
        "type:wordpress-plugin"
      ]
    }
  }
}
```

This library is not being transpiled.

After changing to `type: library` (and being installed under `vendor/`) then it is transpiled.

**Comment by danog** [comment]
Thanks for reporting, will look into this!
